### ISSUE TITLE
Improve 2FA e-mail

### ISSUE THREAD

**Issue by ad2ien** [tchapgouv/synapse-on-k8s#353]
The current e-mail received during 2FA verification is quite laconic. Let's improve it.

**Comment by ad2ien** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EIMIS-6419ddbd85693a00127de149/issues/eimis-ans/eimis-synapse/353?planning-poker) with Zenhub @ad2ien @heroinedor @JDixmier

**Comment by ad2ien** [comment]
We can take advantage of this to have keycloak realm configured to french by default : 
```
    internationalizationEnabled: true
    supportedLocales:
      - "en"
      - "fr"
    defaultLocale: "fr"
```
